-- run_id no tenía default: cada corrida tendría que inventarse el número,
-- y dos runners simultáneos chocarían. Lo genera la base.
alter table public.pipeline_runs
  alter column run_id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.pipeline_runs', 'run_id'),
  coalesce((select max(run_id) from public.pipeline_runs), 0) + 1,
  false
);
